In [ ]:
! pip install Numpy

# **Creating arrays**

In [2]:
import numpy as np

In [ ]:
a = np.array([1, 3, 5])
print(a)


In [5]:
b = np.array([[1,2,6],[4,3,6]])
print(b)

[[1 2 6]
 [4 3 6]]


In [4]:
b = np.array([[[6,5,7],[8,7,9]],[[4,3,6],[4,3,5]]])
print(b)
print(b.shape)

[[[6 5 7]
  [8 7 9]]

 [[4 3 6]
  [4 3 5]]]
(2, 2, 3)


In [ ]:
x = np.arange(10,100,5,dtype=float)

x.reshape(3,6)

In [ ]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)
print(type(x))

2
(3, 6)
18
float64
<class 'numpy.ndarray'>


# **Spacial arrays**

In [ ]:
a = np.ones((3,4),dtype= int)
b = np.zeros((2,3))
c = np.full((2,2),6)
print("a is:",a)
print("\n b is:",b)
print("\n c is:",c)

a is: [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

b is: [[0. 0. 0.]
 [0. 0. 0.]]

c is: [[6 6]
 [6 6]]


In [ ]:
y = np.random.rand(2,3)
y

array([[ 0.45624805,  0.41552727, -0.95404211],
       [ 1.98155032,  0.25525736,  0.72460072]])

In [ ]:
z = np.random.randint(10,100, size= (3,4))
z

array([[26, 17, 62, 62],
       [85, 99, 63, 66],
       [25, 83, 70, 64]])

# **Accessing/Changing specific elements, rows, columns, etc**

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [row_num, col_num]
a[1, 5]

13

In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## **Be careful when copying arrays!!!**

In [ ]:
a = np.array([ 2, 5, 8])
b = a
b[0]=100
print (b)
print(a)

[100   5   8]
[100   5   8]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

# **Array Mathematics**

In [ ]:
a = np.arange(10,20)
a = a.reshape(2,5)
print(a)
b = np.ones((2,5))
print(b)

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
print(a+b)

[[11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


In [ ]:
print(a-b)

[[ 9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18.]]


In [ ]:
print(a*b)

[[10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


In [ ]:
print(a**2)

[[100 121 144 169 196]
 [225 256 289 324 361]]


# np.dot(a,b)
# More information
Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

###Determinant
### Trace
### Singular Vector Decomposition
### Eigenvalues
### Matrix Norm
###Inverse
### Etc...

# **Statistics**

In [8]:
s = np.array([[6,2,3],[4,1,6]])
s

array([[6, 2, 3],
       [4, 1, 6]])

In [9]:
print(np.min(s))
print(np.argmin(s))
print(np.argmin(s,axis = 1))

1
4
[1 1]


In [ ]:
np.max(s, axis=1)

array([6, 6])

In [ ]:
np.sum(s, axis=0)

array([10,  3,  9])

In [ ]:
np.sort(s)

array([[4, 1, 3],
       [6, 2, 6]])

# **Reorganizing Arrays**

In [10]:
# Vertical stacking
v1 = np.array([[6,2,3],[4,1,6]])
v2 = np.array([7,6,9])
print(" v1 shape :",v1.shape)
print(" v2 shape :",v2.shape)


 v1 shape : (2, 3)
 v2 shape : (3,)


In [ ]:
v = np.vstack([v1,v2])
print(v)
print(" v shape :",v.shape)

[[6 2 3]
 [4 1 6]
 [7 6 9]]
 v shape : (3, 3)


In [ ]:
# Horizontal  stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

h = np.hstack((h1,h2))
print(h)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [ ]:
np.savetxt("data.csv",h,delimiter=",")

# **load data**

In [14]:
# load data from file
data = np.genfromtxt('data.txt', delimiter=',')
data = data.astype('int')
print(data)


[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# **Boolean Masking and Advanced Indexing**

In [15]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [16]:
data[data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [17]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [18]:
filedata[:,~(np.any(filedata>50, axis=0))]

array([[ 1, 13, 21, 11,  4,  6,  7,  8,  0,  1,  2,  3],
       [ 3, 42, 12, 33,  4,  4,  3,  4,  5,  6,  7,  0],
       [ 1, 22, 33, 11,  2,  0,  1,  2,  9,  8,  7,  1]])

In [20]:
np.all(data>50,axis=1)

array([False, False, False])

In [21]:
data[:, np.all(data>50,axis=0)]

array([[196],
       [766],
       [999]])

In [24]:
data[((filedata > 50) & (filedata < 100))]

array([75, 75, 55, 78, 76, 88])

In [26]:
a = np. random.randint(-5,10, size = (6,6))
a

array([[ 7,  1, -5, -2,  8,  4],
       [ 6,  2, -1, -4, -4,  7],
       [ 5,  6,  3,  0,  6,  4],
       [ 2,  9, -5,  1,  4,  8],
       [ 0,  3,  7, -3,  8,  7],
       [ 0, -2,  0,  5,  8,  2]])

In [ ]:
a[2:4,0:2]

In [ ]:
a[[0,1,2],[1,2,3]]
a

In [30]:
#Find indices of non-zero elements
r = np.nonzero(a)
print(r)


(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 4, 4, 4, 4, 4, 5, 5, 5, 5]), array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 4, 5, 0, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5, 1, 3, 4, 5]))


In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

In [ ]:
#  Normalize a 5x5 random matrix

Z = np.random.randint(10,size=(5,5))
print(Z)
Z = (Z - np.mean (Z)) / (np.max(Z)-np.min(Z))
print(Z)

In [ ]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)


In [ ]:
# How to find common values between two arrays?
#(function ntersect1dfind the intersection of two arrays and returns the sorted, unique values that are in both of the input arrays.)

Z1 = np.random.randint(0,10,size=(3,3))
print(Z1)
Z2 = np.random.randint(0,10,size=(3,3))
print(Z2)
print(np.intersect1d(Z1,Z2))

In [ ]:
A = np.array([10,4,6,7,1,5,3,4,24,1,1,9,10,10,18])
B = np.array([1,4,5,6,7,8,9])
print(np.in1d(A, B))
C = A[np.in1d(A, B)]
print(C)

In [ ]:
d2 = np. random.choice(["ap", "df", "ks", "ks"], size= (3,3), replace=True, p=None)
print(d2)