In [1]:
import numpy as np

In [21]:
a = np.array([2,5,6], dtype =float)
a

array([2., 5., 6.])

In [9]:
b = np.arange(10,20)
print(np.size(b))

10


In [16]:
c = b.reshape((2,5))
c

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(type(c))

2
(2, 5)
10
int64
<class 'numpy.ndarray'>


In [24]:
a = np.zeros((3,4), dtype = float)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
a = np.full((2,2) ,6)
a

array([[6, 6],
       [6, 6]])

In [ ]:
a = np.zeros((3,4), dtype = float)
a

In [29]:
 d = np.random.randn(3,4)
 d

array([[ 0.5016352 ,  1.16127851,  1.34964403,  1.30559957],
       [ 2.04934141,  0.27206398,  0.07433793,  1.30376792],
       [ 1.55885991, -0.27209512,  1.21266818, -0.27405625]])

In [31]:
d1 = np.random.randint(10,100, 10)
d1

array([77, 35, 84, 54, 86, 85, 20, 36, 79, 67])

In [32]:
c

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
print(c[:,3])

[13 18]


In [34]:
print(c[1,:])

[15 16 17 18 19]


In [35]:
a = np.array([2,4,5])
b = a
b[1]=3
print(b)

[2 3 5]


In [36]:
print(a)

[2 3 5]


In [38]:
a = np.array([2,4,5])
b = a.copy()
b[1]=3
print(b)
print(a)

[2 3 5]
[2 4 5]


In [46]:
a = np.ones((2,3), dtype= int)
b = np.full((3,2),5)

In [43]:
print(a+b)

[[6 6 6]
 [6 6 6]]


In [44]:
print(a*b)

[[5 5 5]
 [5 5 5]]


In [47]:
print(np.dot(a,b))

[[15 15]
 [15 15]]


In [49]:
print(a@b)

[[15 15]
 [15 15]]


In [50]:
d1 = np.random.randint(10,100, 20)
d1

array([91, 20, 32, 20, 44, 54, 93, 30, 53, 86, 89, 44, 70, 69, 74, 79, 53,
       72, 42, 97])

In [51]:
d1 =d1.reshape(4,5)
d1

array([[91, 20, 32, 20, 44],
       [54, 93, 30, 53, 86],
       [89, 44, 70, 69, 74],
       [79, 53, 72, 42, 97]])

In [53]:
print(np.min(d1))
print(np.argmin(d1))

20
1


In [54]:
print(np.min(d1,axis = 1))

[20 30 44 42]


In [56]:
print(np.sum(d1,axis = 0))

[313 210 204 184 301]


In [57]:
# vertical stacking
a = ([2,4,6],[5,3,8])
b = ([2,7,6])
print(a)
print(b)


([2, 4, 6], [5, 3, 8])
[2, 7, 6]


In [60]:
s= np.vstack([a,b])
s

array([[2, 4, 6],
       [5, 3, 8],
       [2, 7, 6]])

In [61]:
a = ([2,4,6],[5,3,8])
b = ([2,7],[5,6])
print(a)
print(b)

([2, 4, 6], [5, 3, 8])
([2, 7], [5, 6])


In [62]:
s= np.hstack([a,b])
s

array([[2, 4, 6, 2, 7],
       [5, 3, 8, 5, 6]])

In [63]:
print(s.shape)

(2, 5)


In [77]:
d = np.genfromtxt("data.txt",delimiter= ",")
d = d.astype("int")
d

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [79]:
print(d.shape)

(3, 18)


In [80]:
d > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [94]:
np.argwhere(d>50)

array([[ 0,  4],
       [ 0,  5],
       [ 1,  4],
       [ 1,  5],
       [ 1,  7],
       [ 2,  4],
       [ 2,  8],
       [ 2, 16],
       [ 2, 17]])

In [89]:
d [:,0:6]

array([[  1,  13,  21,  11, 196,  75],
       [  3,  42,  12,  33, 766,  75],
       [  1,  22,  33,  11, 999,  11]])

In [87]:
# any , all
np.any(d >50 , axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [96]:
d[:,~ np.any(d >50 , axis=0)]

array([[ 1, 13, 21, 11,  4,  6,  7,  8,  0,  1,  2,  3],
       [ 3, 42, 12, 33,  4,  4,  3,  4,  5,  6,  7,  0],
       [ 1, 22, 33, 11,  2,  0,  1,  2,  9,  8,  7,  1]])